### ISSUE TITLE
Synthesize Action: TypeError On Docker

### ISSUE THREAD

**Issue by treid003** [oduwsdl/hypercane#13]
When using the synthesize action on Docker a type error occurs ("TypeError: 'Namespace' object is not iterable"). 

The command I used is listed below:
    hc synthesize warcs -i archiveit -a 7760 -o South_Louisiana_Flood

![sythesize_action_error_docker_windows](https://user-images.githubusercontent.com/31581841/85488506-67d8ab80-b59c-11ea-82c8-d26feec4fca0.png)

**Comment by shawnmjones** [comment]
I have reproduced this...

```
# docker-compose run hypercane hc synthesize warcs -i archiveit -a 7760 -o South_Louisiana_Flood                                                                                           0
Starting hypercane_mongodb_1 ... done
/usr/local/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/local/bin/hc", line 105, in <module>
    sys.argv[3:])
  File "/usr/local/lib/python3.7/site-packages/hypercane/actions/synthesize.py", line 329, in synthesize_warcs
    args = process_input_args(args, parser)
  File "/usr/local/lib/python3.7/site-packages/hypercane/actions/synthesize.py", line 22, in process_input_args
    args = parser.parse_args(args)
  File "/usr/local/lib/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/argparse.py", line 1761, in parse_known_args
    args = list(args)
TypeError: 'Namespace' object is not iterable
```

**Comment by shawnmjones** [comment]
This issue does not happen in a clean Python [virtualenv](https://pypi.org/project/virtualenv/) on macOS 10.15.5.

```
# hc synthesize warcs -i archiveit -a 7760 -o ~/tmp/South_Louisiana_Flood                                                                                                                  
2020-06-23 19:34:52,667 [INFO] hypercane.actions.synthesize: Starting generation of files from input
2020-06-23 19:34:52,668 [INFO] hypercane.identify: processing input for type archiveit
2020-06-23 19:34:52,668 [INFO] hypercane.identify: discovering mementos for input type archiveit
2020-06-23 19:34:57,815 [INFO] hypercane.identify: discovered 359 URIs
2020-06-23 19:34:57,815 [INFO] hypercane.actions.synthesize: discovered 359 URI-Ms from the input
2020-06-23 19:34:57,816 [INFO] hypercane.actions.synthesize: Output directory /Users/smj/tmp/South_Louisiana_Flood does not exist, creating...
2020-06-23 19:40:48,848 [INFO] hypercane.actions.synthesize: Done generating directory of files, output is at /Users/smj/tmp/South_Louisiana_Flood
```

It is definitely a problem with the Docker configuration.

**Comment by shawnmjones** [comment]
Like the stacktrace states, the problem is on line 22 of hypercane/actions/synthesize.py:

https://github.com/oduwsdl/hypercane/blob/e9dff855cb2848e8b9754160ffcdfab8843f16be/hypercane/actions/synthesize.py#L18-L22

There is a duplicate call to `parser.parse_args`. I do not know why I inserted it. I'm going to run some tests inside and outside Docker. It definitely fails in Docker, but works fine in macOS. ¯\_(ツ)_/¯
